project:
  type: website
  output-dir: _site

website:
  title: "Jinsung Sur — Biostat777 intro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example-analysis.qmd
        text: Project 1 Example analysis
      - href: project2.qmd
        text: Project 2
  page-footer:
    left: "© {{< meta author >}}"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-tools: true
    number-sections: false
    smooth-scroll: true
    css: styles.css

metadata-files:
  - _meta.yml
